[package]
name = "blazecast"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = [ 
    "global-shortcut-all", "shell-open", "system-tray", 
    "global-shortcut", "window-hide", "window-show", 
    "window-close", "window-set-focus"
]}
serde = { version = "1", features = ["derive"] }
serde_json = "1"
walkdir = "2.3"
windows-registry = "0.4.0"
windows = { version = "0.51", features = [
    "Win32_Foundation",
    "Win32_UI_Shell",
    "Win32_System_Com",
    "Win32_Graphics_Gdi",
    "Win32_UI_WindowsAndMessaging",
]}
image = "0.24.7"
base64 = "0.21.0"
lazy_static = "1.4.0"

[features]
custom-protocol = ["tauri/custom-protocol"]