blank_issues_enabled: false
contact_links:
  - name: Ask a Question or Get Help
    url: https://github.com/yourusername/blazecast/discussions
    about: Please ask questions or request help in Discussions instead of opening an issue.
